// Generated by CoffeeScript 2.2.1
(function() {
  var SomeClass;

  SomeClass = class SomeClass {
    constructor(initStr) {
      this.initStr = initStr;
    }

    get() {
      return this.initStr;
    }

  };

  module.exports = SomeClass;

}).call(this);

//# sourceMappingURL=SomeClass.js.map
