// Generated by CoffeeScript 2.2.1
(function() {
  var SomeClass2;

  SomeClass2 = class SomeClass2 {
    constructor(initStr) {
      this.initStr = initStr;
    }

    get() {
      return this.initStr;
    }

  };

  module.exports = SomeClass2;

}).call(this);

//# sourceMappingURL=SomeClass2.js.map
